import type { SystemFlowEdge, SystemFlowNode } from './types'

export const seedNodes: SystemFlowNode[] = [
  {
    id: 'clients',
    type: 'system',
    position: { x: 20, y: 230 },
    data: {
      kind: 'client',
      label: 'Clients',
      health: 'healthy',
      detail: '10k req/s',
      load: 1,
    },
  },
  {
    id: 'edge',
    type: 'system',
    position: { x: 230, y: 230 },
    data: {
      kind: 'gateway',
      label: 'Edge',
      health: 'healthy',
      detail: '3ms edge',
      load: 1,
    },
  },
  {
    id: 'api',
    type: 'system',
    selected: true,
    position: { x: 440, y: 230 },
    data: {
      kind: 'service',
      label: 'Short Link API',
      health: 'healthy',
      detail: 'Ready',
      load: 1,
    },
  },
  {
    id: 'cache',
    type: 'system',
    position: { x: 665, y: 230 },
    data: {
      kind: 'cache',
      label: 'Redis',
      health: 'healthy',
      detail: 'Warm',
      load: 1,
    },
  },
  {
    id: 'database',
    type: 'system',
    position: { x: 900, y: 230 },
    data: {
      kind: 'database',
      label: 'Primary DB',
      health: 'healthy',
      detail: 'Ready',
      load: 1,
    },
  },
  {
    id: 'queue',
    type: 'system',
    position: { x: 625, y: 480 },
    data: {
      kind: 'queue',
      label: 'Queue',
      health: 'healthy',
      detail: 'Draining',
      load: 1,
    },
  },
]

export const seedEdges: SystemFlowEdge[] = [
  {
    id: 'clients-edge',
    type: 'traffic',
    source: 'clients',
    target: 'edge',
    sourceHandle: 'right',
    targetHandle: 'left',
    label: '10k req/s',
    data: { tone: 'healthy', intensity: 1, paused: false },
  },
  {
    id: 'edge-api',
    type: 'traffic',
    source: 'edge',
    target: 'api',
    sourceHandle: 'right',
    targetHandle: 'left',
    data: { tone: 'healthy', intensity: 1, paused: false },
  },
  {
    id: 'api-cache',
    type: 'traffic',
    source: 'api',
    target: 'cache',
    sourceHandle: 'right',
    targetHandle: 'left',
    label: '7% miss',
    data: { tone: 'healthy', intensity: 1, paused: false },
  },
  {
    id: 'api-database',
    type: 'traffic',
    source: 'api',
    target: 'database',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    label: '1k req/s · miss path',
    data: {
      tone: 'healthy',
      intensity: 1,
      paused: false,
      flowRatio: 0.1,
      labelOffsetX: 60,
      labelOffsetY: 128,
    },
  },
  {
    id: 'api-queue',
    type: 'traffic',
    source: 'api',
    target: 'queue',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    data: { tone: 'healthy', intensity: 3, paused: false },
  },
]
